### PR TITLE
Symbol type in Java

### PR DESCRIPTION
**Pull request by akimd**
Bison 3.6 brings a few important changes in all the skeletons, but I am no Java programmer, and there are things I don't know how to do.  Because it has a significant impact on the API, I would like to avoid stupid mistakes with which, because of backward compatibility, we might have to live for a long time.

So _please_, if you are knowledgeable in Java, help me!

One of the most significant changes in Bison 3.6 is that we move from plain int types to store the internal symbol kind (`PLUS`, `LPAREN`, `NUMBER`, etc.) to an enum.  The motivation is that before the symbol kinds were hidden from the user, but now they have to be exposed for the real new feature of 3.6: customized error messages.

Let me take examples/java/calc.y as an example:

```
%token
    BANG   "!"
    PLUS   "+"
    MINUS  "-"
    STAR   "*"
    SLASH  "/"
    CARET  "^"
    LPAREN "("
    RPAREN ")"
    EQUAL  "="
    EOL    _("end of line")
  <Integer>
    NUM    _("number")
```

This generates the following enum (don't pay too much attention to its name, it's likely to change from `SymbolType` to `symbolKind`):

``` java
public enum SymbolType
{
    YYSYMBOL_YYEMPTY(-2),
    YYSYMBOL_YYEOF(0),
    YYSYMBOL_YYERROR(1),
    YYSYMBOL_YYUNDEF(2),
    YYSYMBOL_BANG(3),
    YYSYMBOL_PLUS(4),
    YYSYMBOL_MINUS(5),
    YYSYMBOL_STAR(6),
    YYSYMBOL_SLASH(7),
    YYSYMBOL_CARET(8),
    YYSYMBOL_LPAREN(9),
    YYSYMBOL_RPAREN(10),
    YYSYMBOL_EQUAL(11),
    YYSYMBOL_EOL(12),
    YYSYMBOL_NUM(13),
    YYSYMBOL_NEG(14),
    YYSYMBOL_YYACCEPT(15),
    YYSYMBOL_input(16),
    YYSYMBOL_line(17),
    YYSYMBOL_exp(18),
    YYNTOKENS(15); ///< Number of tokens.

    private int code;

    SymbolType (int n) {
        this.code = n;
    }
    static SymbolType get (int code) {
        switch (code) {
        default: return YYSYMBOL_YYUNDEF;
        case 0: return SymbolType.YYSYMBOL_YYEOF;
        case 1: return SymbolType.YYSYMBOL_YYERROR;
        case 2: return SymbolType.YYSYMBOL_YYUNDEF;
        case 3: return SymbolType.YYSYMBOL_BANG;
        case 4: return SymbolType.YYSYMBOL_PLUS;
        case 5: return SymbolType.YYSYMBOL_MINUS;
        case 6: return SymbolType.YYSYMBOL_STAR;
        case 7: return SymbolType.YYSYMBOL_SLASH;
        case 8: return SymbolType.YYSYMBOL_CARET;
        case 9: return SymbolType.YYSYMBOL_LPAREN;
        case 10: return SymbolType.YYSYMBOL_RPAREN;
        case 11: return SymbolType.YYSYMBOL_EQUAL;
        case 12: return SymbolType.YYSYMBOL_EOL;
        case 13: return SymbolType.YYSYMBOL_NUM;
        case 14: return SymbolType.YYSYMBOL_NEG;
        case 15: return SymbolType.YYSYMBOL_YYACCEPT;
        case 16: return SymbolType.YYSYMBOL_input;
        case 17: return SymbolType.YYSYMBOL_line;
        case 18: return SymbolType.YYSYMBOL_exp;
        }
    }
    int getCode () {
        return this.code;
    }
};
```

So it's kind of heavy weight: we are carrying a fully blown object for each single instance of SymbolType.  And we have to use the class method `SymbolType.get()` to find the enum from its numerical code:

```java
private static final SymbolType yytranslate_ (int t)
{
  int user_token_number_max_ = 269;
  if (t <= 0)
    return SymbolType.YYSYMBOL_YYEOF;
  else if (t <= user_token_number_max_)
    return SymbolType.get (yytranslate_table_[t]);   // ****************
  else
    return SymbolType.YYSYMBOL_YYUNDEF;
}
```

and to use the object method `SymbolType.getCode()` to find the numerical code of an enum.

```Java
yyn += yytoken.getCode ();
if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yytoken.getCode ())
  label = YYDEFAULT;
```

The JVMs are known to be quite good at optimizing, but I have no idea whether this abstraction will be zero-cost or not.

So I would definitely need some feedback.  Is this the right move for Java?  Or should we stick to some plain integral type (on which we would have no type checking).

Obviously the `YYSYMBOL_` prefix in the enums seems redundant.  That detail will be taken care of later, don't pay attention to this now either.

Cheers!

### CODE REVIEW

**Comment by akimd** [comment]
@dgageot If you have some spare time, I'd be happy to have your opinion!

**Comment by bonzini** [comment]
Hi, it looks good but I would: 1) use an array instead of a switch statement for `get()` 2) declare everything in the public interface as `final` so the VM has an easier job deciding what it can inline.

**Comment by akimd** [comment]
Hi @bonzini!  Many thanks for the review!

> Hi, it looks good but I would: 1) use an array instead of a switch statement for `get()` 2) declare everything in the public interface as `final` so the VM has an easier job deciding what it can inline.

I did both things, thanks a lot!

So you confirm this is right?  I'm afraid there could be a performance hit.  Am I being paranoid here?

**Comment by bonzini** [comment]
With the array instead of the switch statement it should be okay.

**Comment by dgageot** [comment]
Hi @akimd! Enums tend to have good perf in Java. In terms in memory, there's only one instance of each distinct value. In terms of inlining, the type itself and all of its methods are final, no matter what. So the code looks all good to me!

**Comment by akimd** [comment]
Thanks to both of you, @bonzini and @dgageot.  Installed!

Cheers!

**Pull request merged**
